// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDittF283VtEzgPEEC6wtZL_vdHGuHdgrk',
    appId: '1:480060335010:web:c3a43ea9a6dcd8baa588fb',
    messagingSenderId: '480060335010',
    projectId: 'tracex-21f6b',
    authDomain: 'tracex-21f6b.firebaseapp.com',
    storageBucket: 'tracex-21f6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG9ix8l6Yp0JbI11FYZ5jMDxNHCYGcChg',
    appId: '1:480060335010:android:d803e6586a3d5e9ca588fb',
    messagingSenderId: '480060335010',
    projectId: 'tracex-21f6b',
    storageBucket: 'tracex-21f6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmJwk1GlZroQlKX8wnDXkURlpxtWkuF2Y',
    appId: '1:480060335010:ios:94c8dd962adf03b1a588fb',
    messagingSenderId: '480060335010',
    projectId: 'tracex-21f6b',
    storageBucket: 'tracex-21f6b.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmJwk1GlZroQlKX8wnDXkURlpxtWkuF2Y',
    appId: '1:480060335010:ios:94c8dd962adf03b1a588fb',
    messagingSenderId: '480060335010',
    projectId: 'tracex-21f6b',
    storageBucket: 'tracex-21f6b.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDittF283VtEzgPEEC6wtZL_vdHGuHdgrk',
    appId: '1:480060335010:web:d2d912ba8ab7998ba588fb',
    messagingSenderId: '480060335010',
    projectId: 'tracex-21f6b',
    authDomain: 'tracex-21f6b.firebaseapp.com',
    storageBucket: 'tracex-21f6b.firebasestorage.app',
  );
}
